name: WriteToGoogleSheet

on:
  schedule:
      - cron: '0 21 * * *'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Running
      run: |
        echo "Running!"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pygsheets
        pip install numpy
        pip install google-auth
        pip install datetime
        pip install pytz
        pip install plotly

    - name: Run WriteToGoogleSheet.py
      env: 
        GAPI: ${{secrets.GAPI}} 
      run: |
        python ./WriteToGoogleSheet.py